site_name: MirInsider
copyright: Copyright &copy; 2021-2022 Ralvine
site_url: https://ralvine.github.com/mirinsider/
theme:
  icon:
    logo: material/salesforce
  name: material
  custom_dir: overrides
  logo: https://s1.ax1x.com/2023/02/09/pSWiXlR.png
  favicon: https://s1.ax1x.com/2023/02/09/pSWiXlR.png
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    #- navigation.tabs.sticky
    - navigation.indexes
    - navigation.top
    #- navigation.expand
    - navigation.footer
    - search.highlight
    - search.share
  language: zh
  palette: 
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/weather-sunny
        name: åˆ‡æ¢å¤œé—´æ¨¡å¼
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/weather-night
        name: åˆ‡æ¢æ—¥é—´æ¨¡å¼
  font:
      text: Share Tech
      code: JetBrains Mono
markdown_extensions:
  - toc:
      permalink: ğŸ·
      permalink_title: è·³è½¬åˆ°è¯¥éƒ¨åˆ†
  - meta
  - pymdownx.tabbed:
      alternate_style: true 
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      use_pygments: true
      linenums: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - attr_list
  - md_in_html
  - admonition
  - footnotes
  - def_list
  - pymdownx.details
  - pymdownx.superfences
plugins:
  - glightbox
  - git-revision-date-localized:
      enable_creation_date: true
      type: iso_date
  - search
  - tags
  - tags:
      enabled: !ENV [CI, false]
      tags_file: home/tags.md
extra:
  analytics:
    provider: google
    property: G-5ECDD2TBHN
    feedback:
      title: æœ¬é¡µé¢å¯¹æ‚¨æœ‰å¸®åŠ©å—ï¼Ÿ
      ratings:
        - icon: material/emoticon-happy-outline
          name: å¾ˆæœ‰å¸®åŠ©ï¼
          data: 1
          note: >-
            è°¢è°¢æ‚¨çš„åé¦ˆï¼
        - icon: material/emoticon-sad-outline
          name: äºŸå¾…æ”¹è¿›ã€‚
          data: 0
          note: >- 
            æ„Ÿè°¢æ‚¨çš„åé¦ˆï¼æ¬¢è¿é€šè¿‡è®¿é—®æˆ‘ä»¬çš„ <a href="https://ralvine.github.io/" target="_blank" rel="noopener">åšå®¢</a>ä»¥æå‡ºè¿›ä¸€æ­¥å»ºè®®ã€‚
  social:
    - icon: fontawesome/brands/github
      link: https://ralvine.github.io/
      name: è®¿é—®Ralvineçš„åšå®¢
    - icon: fontawesome/brands/alipay
      link: https://ralvine.github.io/
      name: è®¿é—®Ralvineçš„åšå®¢
    - icon: fontawesome/brands/apple
      link: https://ralvine.github.io/
      name: è®¿é—®Ralvineçš„åšå®¢
    - icon: fontawesome/brands/steam
      link: https://ralvine.github.io/
      name: è®¿é—®Ralvineçš„åšå®¢
    - icon: fontawesome/brands/telegram
      link: https://ralvine.github.io/
      name: è®¿é—®Ralvineçš„åšå®¢
    - icon: fontawesome/brands/twitter
      link: https://ralvine.github.io/
      name: è®¿é—®Ralvineçš„åšå®¢
    - icon: fontawesome/brands/weibo
      link: https://ralvine.github.io/
      name: è®¿é—®Ralvineçš„åšå®¢
    - icon: fontawesome/brands/weixin
      link: https://ralvine.github.io/
      name: è®¿é—®Ralvineçš„åšå®¢
    - icon: fontawesome/brands/youtube
      link: https://ralvine.github.io/
      name: è®¿é—®Ralvineçš„åšå®¢
    - icon: fontawesome/brands/zhihu
      link: https://ralvine.github.io/
      name: è®¿é—®Ralvineçš„åšå®¢
extra_css:
  - css/extra.css
extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
nav:
  - "ğŸ“é•œç»":
    - index.md
    - "ğŸ‘¨ç®€ä»‹": home/brief.md
    - "ğŸ·ï¸æ ‡ç­¾": home/tags.md
  - "ğŸ–‹ï¸è¯šæ³çš„å‚ä¸è€…": 
    - memo/index.md
    - "æ—…è¡Œ":
      - memo/travel/index.md
      - memo/travel/chuanyu.md
      - memo/travel/tibet.md
    - "å…¬ç›Šå®è·µ":
      - memo/commonweal/mathqa22.md
      - memo/commonweal/xncx.md
      - memo/commonweal/zhijiao22.md
      - memo/activity/highschool.md
      - memo/activity/winter21.md
      - memo/activity/winter22.md
      - memo/activity/shiyu.md
    - "ç§‘ç«è®­ç»ƒ":
      - memo/project/tran.md
      - memo/project/apmcm.md
      - memo/project/mathshanshu.md
      - memo/project/mathshenzh.md
      - memo/project/mcm22.md
      - memo/project/modelzhcn.md
      - memo/project/modelzju.md
      - memo/project/srtp.md
    - "å­¦å·¥ç¤¾å›¢":
      - memo/team/test.md
      - "æ±‚æ˜¯æ½®å·¥ä½œå›¢é˜Ÿ":
        - memo/team/qsc/test.md
        - memo/team/qsc/test.md
      - "å›¢å§”å­¦ç”Ÿæ–‡ä½“ä¸­å¿ƒ":
        - memo/team/wenti/test.md
        - memo/team/wenti/test.md
      - "ä¿¡è®¡å…šæ”¯éƒ¨":
        - memo/team/party/test.md
        - memo/team/party/test.md
      - "ç«ºå¯æ¡¢å­¦é™¢ITP":
        - memo/team/itp/test.md
        - memo/team/itp/test.md
      - "ZJUMSC":
        - memo/team/msc/test.md
  - "ğŸ—’ç¬ƒè¡Œçš„æ¢ç´¢è€…": 
    - notes/index.md
    - notes/timeline.md
    - "æ—¶ä¸‹è¯¾ä¸š: 2022-2023æ˜¥å¤":
      - notes/course/3d/index.md
      - notes/course/3d/fhfx.md
      - notes/course/3d/oop.md
      - notes/course/3d/fbhs.md
      - notes/course/3d/sbhs.md
      - notes/course/3d/sjjmyfx.md
      - notes/course/3d/pdeszj.md
      - notes/course/3d/zzjjx.md
    - "æµ™æ±Ÿå¤§å­¦æœ¬ç§‘ç”Ÿè¯¾ç¨‹":
      - notes/course/index.md
      - "2022-2023ç§‹å†¬":
        - notes/course/3u/data.md
        - notes/course/3u/quan.md
        - notes/course/3u/xigai.md
        - notes/course/3u/eco.md
        - notes/course/3u/na.md
        - notes/course/3u/syms.md
        - notes/course/3u/pde22.md
        - notes/course/3u/gll.md
        - notes/course/3u/alg.md
        - notes/course/3u/soft.md
      - "2021-2022æ˜¥å¤":
        - notes/course/2d/model.md
        - notes/course/2d/pde.md
        - notes/course/2d/tdgt.md
        - notes/course/2d/szds.md
        - notes/course/2d/mg.md
        - notes/course/2d/ec.md
        - notes/course/2d/junli.md
        - notes/course/2d/guanli.md
      - "2021-2022ç§‹å†¬":
        - notes/course/2u/ds.md
        - notes/course/2u/sf3.md
        - notes/course/2u/my.md
        - notes/course/2u/ggjj.md
        - notes/course/2u/dxwl2.md
        - notes/course/2u/dxwlsy.md
        - notes/course/2u/ode.md
      - "2020-2021æ˜¥å¤":
        - notes/course/1d/wxqy.md
        - notes/course/1d/dxwl.md
        - notes/course/1d/jds.md
        - notes/course/1d/xc.md
        - notes/course/1d/sf2.md
        - notes/course/1d/dxyy4.md
        - notes/course/1d/zhigui.md
      - "2020-2021ç§‹å†¬":
        - notes/course/1u/dxyy3.md
        - notes/course/1u/sx.md
        - notes/course/1u/sf.md
        - notes/course/1u/skd.md
        - notes/course/1u/skdsy.md
        - notes/course/1u/mks.md
        - notes/course/1u/jjf.md
        - notes/course/1u/jihe.md
        - notes/course/1u/djj.md
    - "æ•°æ®ä¸ä¿¡æ¯ç§‘å­¦":
      - notes/data/index.md
      - notes/data/test.md
    - "äººå·¥æ™ºèƒ½&æœºå™¨å­¦ä¹ ":
      - notes/ai/index.md
      - notes/ai/cs188.md
      - notes/ai/cs229.md
    - "å…¨æ ˆå¼€å‘":
      - notes/code/index.md
      - notes/code/cplusplus.md
      - notes/code/html-css.md
      - notes/code/docker.md
      - notes/code/note0.md
      - notes/code/latex.md
      - notes/code/vue.md
      - notes/code/electron.md
      - notes/code/flutter.md
      - notes/code/swiftui.md
    - "æ‘„å½±ä¸å½±åƒåˆ›ä½œ":
      - notes/create/index.md
      - notes/create/webs.md
      - notes/create/fcpx.md
    - "ç¼–æ›²":
      - notes/product/index.md
      - notes/product/test.md
  - "ğŸ“šå¿ å®çš„è®°å½•è€…": 
    - view/index.md
    - view/timeline.md
    - "ä¹¦ç±":
      - view/books/liucx.md
      - view/books/longnight.md
      - view/books/qpdzsgr.md
    - "ç”µå½±ä¸å‰§é›†":
      - view/music/lyric.md
    - "è§†é¢‘æ”¶è—å¤¹":
      - "ç§‘æŠ€è¯„æµ‹":
        - view/video/tech/surface.md
      - "ç¤¾å“²å¿ƒç†":
        - view/video/psy/love.md
        - view/video/psy/relate.md
      - "ä¹¦å½±æº¯æ":
        - view/video/eyes/jjnz.md
        - view/video/eyes/mysx.md