site_name: MirInsider é•œå¹•
copyright: Copyright &copy; 2021-2022 Ralvine
site_url: https://ralvine.github.com/mirinsider/
theme:
  icon:
    logo: material/salesforce
  name: material
  custom_dir: overrides
  logo: images/logo.png # logo
  favicon: images/favicon.png
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    #- navigation.tabs.sticky
    - navigation.indexes
    - navigation.top
    #- navigation.expand
    - navigation.footer
    - search.highlight
    - search.share
  language: zh
  palette: 
    - scheme: default
      toggle:
        icon: material/weather-sunny
        name: åˆ‡æ¢å¤œé—´æ¨¡å¼
    - scheme: slate
      toggle:
        icon: material/weather-night
        name: åˆ‡æ¢æ—¥é—´æ¨¡å¼
  font:
      text: Share Tech
      code: JetBrains Mono
markdown_extensions:
  - toc:
      permalink: true
      permalink_title: è·³è½¬åˆ°è¯¥éƒ¨åˆ†
  - meta
  - pymdownx.tabbed:
      alternate_style: true 
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      use_pygments: true
      linenums: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - attr_list
  - md_in_html
  - admonition
  - footnotes
  - def_list
  - pymdownx.details
  - pymdownx.superfences
plugins:
  - glightbox
  - git-revision-date-localized:
      enable_creation_date: true
      type: iso_date
  - search
  - tags
  - tags:
      enabled: !ENV [CI, false]
      tags_file: home/tags.md
extra:
  analytics:
    provider: google
    property: G-5ECDD2TBHN
    feedback:
      title: æœ¬é¡µé¢å¯¹æ‚¨æœ‰å¸®åŠ©å—ï¼Ÿ
      ratings:
        - icon: material/emoticon-happy-outline
          name: å¾ˆæœ‰å¸®åŠ©ï¼
          data: 1
          note: >-
            è°¢è°¢æ‚¨çš„åé¦ˆï¼
        - icon: material/emoticon-sad-outline
          name: äºŸå¾…æ”¹è¿›ã€‚
          data: 0
          note: >- 
            æ„Ÿè°¢æ‚¨çš„åé¦ˆï¼æ¬¢è¿é€šè¿‡è®¿é—®æˆ‘ä»¬çš„ <a href="https://ralvine.github.io/" target="_blank" rel="noopener">åšå®¢</a>ä»¥æå‡ºè¿›ä¸€æ­¥å»ºè®®ã€‚
  social:
    - icon: fontawesome/brands/github
      link: https://ralvine.github.io/
      name: è®¿é—®Ralvineçš„åšå®¢
    - icon: fontawesome/brands/alipay
      link: https://ralvine.github.io/
      name: è®¿é—®Ralvineçš„åšå®¢
    - icon: fontawesome/brands/apple
      link: https://ralvine.github.io/
      name: è®¿é—®Ralvineçš„åšå®¢
    - icon: fontawesome/brands/steam
      link: https://ralvine.github.io/
      name: è®¿é—®Ralvineçš„åšå®¢
    - icon: fontawesome/brands/telegram
      link: https://ralvine.github.io/
      name: è®¿é—®Ralvineçš„åšå®¢
    - icon: fontawesome/brands/twitter
      link: https://ralvine.github.io/
      name: è®¿é—®Ralvineçš„åšå®¢
    - icon: fontawesome/brands/weibo
      link: https://ralvine.github.io/
      name: è®¿é—®Ralvineçš„åšå®¢
    - icon: fontawesome/brands/weixin
      link: https://ralvine.github.io/
      name: è®¿é—®Ralvineçš„åšå®¢
    - icon: fontawesome/brands/youtube
      link: https://ralvine.github.io/
      name: è®¿é—®Ralvineçš„åšå®¢
    - icon: fontawesome/brands/zhihu
      link: https://ralvine.github.io/
      name: è®¿é—®Ralvineçš„åšå®¢
extra_css:
  - css/extra.css
extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
nav:
  - "ğŸ“å®¢å»Š":
    - index.md
    - "ğŸ‘¨ç®€ä»‹": home/brief.md
    - "ğŸ·ï¸æ ‡ç­¾": home/tags.md
  - "ğŸ–‹ï¸èƒ¶å·": 
    - memo/index.md
    - "æ—…è¡Œ":
      - memo/travel/index.md
      - memo/travel/chuanyu.md
      - memo/travel/tibet.md
    - "å…¬ç›ŠæœåŠ¡":
      - memo/commonweal/mathqa22.md
      - memo/commonweal/xncx.md
      - memo/commonweal/zhijiao22.md
    - "å®è·µæ´»åŠ¨":
      - memo/activity/highschool.md
      - memo/activity/winter21.md
      - memo/activity/winter22.md
    - "å­¦æœ¯é¡¹ç›®":
      - memo/project/tran.md
      - memo/project/apmcm.md
      - memo/project/mathshanshu.md
      - memo/project/mathshenzh.md
      - memo/project/mcm22.md
      - memo/project/modelzhcn.md
      - memo/project/modelzju.md
      - memo/project/srtp.md
    - "ç»„ç»‡å·¥ä½œ":
      - memo/team/test.md
      - "æ±‚æ˜¯æ½®å·¥ä½œå›¢é˜Ÿ":
        - memo/team/qsc/test.md
        - memo/team/qsc/test.md
      - "å›¢å§”å­¦ç”Ÿæ–‡ä½“ä¸­å¿ƒ":
        - memo/team/wenti/test.md
        - memo/team/wenti/test.md
      - "ä¿¡è®¡å…šæ”¯éƒ¨":
        - memo/team/party/test.md
        - memo/team/party/test.md
      - "ç«ºå¯æ¡¢å­¦é™¢ITP":
        - memo/team/itp/test.md
        - memo/team/itp/test.md
      - "ZJUMSC":
        - memo/team/msc/test.md
  - "ğŸ“é•œè§‚": 
    - library/index.md
    - "è¯„è®º":
      - library/review/news-1.md
      - library/review/news-2.md
      - library/review/news-3.md
      - library/review/fsz-1.md
      - library/review/fsz-2.md
      - library/review/mks-1.md
      - library/review/mks-2.md
      - library/review/jzm-1.md
      - library/review/mqz-1.md
      - library/review/mqz-2.md
      - library/review/mqz-3.md
      - library/review/mzd-1.md
      - library/review/slz-1.md
      - library/review/slz-2.md
      - library/review/ygz-1.md
      - library/review/ygz-2.md
    - "æŠ¥é“":
      - library/report/hyb.md
      - library/report/tzhy.md
      - library/report/zfcg.md
      - library/report/ghth.md
      - library/report/jdgk.md
      - library/report/gkch.md
      - library/report/ldr.md
      - library/report/ldrtx.md
      - library/report/zyzfw.md
      - library/report/united-1.md
      - library/report/united-2.md
      - library/report/wqs-1.md
      - library/report/wqs-2.md
      - library/report/wqs-3.md
      - library/report/wjb-1.md
      - library/report/zjw-1.md
      - library/report/zjw-2.md
    - "æ–‡çŒ®":
      - library/files/xjp-1.md
      - library/files/xjp-2.md
      - library/files/xjp-3.md
      - library/files/xjp-4.md
      - library/files/xjp-5.md
      - library/files/xjp-6.md
      - library/files/zy23-1.md
  - "ğŸ—’é‚»åŸŸ": 
    - notes/index.md
    - "è®¡ç®—æœºç§‘å­¦":
      - notes/cs/index.md
      - "æ•°æ®åˆ†æ":
        - notes/cs/data/test.md
      - "äººå·¥æ™ºèƒ½&æœºå™¨å­¦ä¹ ":
        - notes/cs/ai/cs188.md
        - notes/cs/ai/cs229.md
      - "å¼€å‘":
        - notes/cs/code/cplusplus.md
        - notes/cs/code/html-css.md
        - notes/cs/code/docker.md
        - notes/cs/code/note0.md
    - "æµ™æ±Ÿå¤§å­¦æœ¬ç§‘ç”Ÿè¯¾ç¨‹":
      - "2022-2023ç§‹å†¬":
        - notes/course/3u/data.md
        - notes/course/3u/quan.md
        - notes/course/3u/xigai.md
        - notes/course/3u/eco.md
        - notes/course/3u/na.md
        - notes/course/3u/syms.md
        - notes/course/3u/pde22.md
        - notes/course/3u/gll.md
        - notes/course/3u/alg.md
        - notes/course/3u/soft.md
      - "2021-2022æ˜¥å¤":
        - notes/course/2d/model.md
        - notes/course/2d/pde.md
        - notes/course/2d/tdgt.md
        - notes/course/2d/szds.md
        - notes/course/2d/mg.md
        - notes/course/2d/ec.md
        - notes/course/2d/junli.md
        - notes/course/2d/guanli.md
      - "2021-2022ç§‹å†¬":
        - notes/course/2u/ds.md
        - notes/course/2u/sf3.md
        - notes/course/2u/my.md
        - notes/course/2u/ggjj.md
        - notes/course/2u/dxwl2.md
        - notes/course/2u/dxwlsy.md
        - notes/course/2u/ode.md
      - "2020-2021æ˜¥å¤":
        - notes/course/1d/wxqy.md
        - notes/course/1d/dxwl.md
        - notes/course/1d/jds.md
        - notes/course/1d/xc.md
        - notes/course/1d/sf2.md
        - notes/course/1d/dxyy4.md
        - notes/course/1d/zhigui.md
      - "2020-2021ç§‹å†¬":
        - notes/course/1u/dxyy3.md
        - notes/course/1u/sx.md
        - notes/course/1u/sf.md
        - notes/course/1u/skd.md
        - notes/course/1u/skdsy.md
        - notes/course/1u/mks.md
        - notes/course/1u/jjf.md
        - notes/course/1u/jihe.md
        - notes/course/1u/djj.md
    - "äº§å“æ¶æ„":
      - notes/product/test.md
    - "æ•°å­—åˆ›ä½œ":
      - notes/create/webs.md
      - notes/create/fcpx.md
  - "ğŸ“šç›®ä½™": 
    - view/index.md
    - "ä¹¦ç±":
      - view/books/liucx.md
      - view/books/longnight.md
      - view/books/qpdzsgr.md
    - "éŸ³ä¹":
      - view/music/lyric.md
    - "è§†é¢‘":
      - view/video/surface.md