site_name: MirInsider é•œå¹•
copyright: Copyright &copy; 2021-2022 Ralvine
site_url: https://ralvine.github.com/mirinsider/
theme:
  icon:
    logo: material/salesforce
  name: material
  favicon: images/favicon.png
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - search.highlight
    - navigation.expand
    - navigation.footer
  language: zh
  palette: 
    - primary: white
      toggle:
        icon: material/weather-sunny
        name: åˆ‡æ¢å¤œé—´æ¨¡å¼
    - scheme: slate
      primary: black
      toggle:
        icon: material/weather-night
        name: åˆ‡æ¢æ—¥é—´æ¨¡å¼
  font:
      text: Share Tech
      code: JetBrains Mono
markdown_extensions:
  - md_in_html
  - meta
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      use_pygments: true
      linenums: true
  - attr_list
  - pymdownx.superfences
  - footnotes
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://ralvine.github.io/
      name: è®¿é—®Ralvineçš„åšå®¢
    - icon: fontawesome/brands/alipay
      link: https://ralvine.github.io/
      name: è®¿é—®Ralvineçš„åšå®¢
    - icon: fontawesome/brands/apple
      link: https://ralvine.github.io/
      name: è®¿é—®Ralvineçš„åšå®¢
    - icon: fontawesome/brands/steam
      link: https://ralvine.github.io/
      name: è®¿é—®Ralvineçš„åšå®¢
    - icon: fontawesome/brands/telegram
      link: https://ralvine.github.io/
      name: è®¿é—®Ralvineçš„åšå®¢
    - icon: fontawesome/brands/twitter
      link: https://ralvine.github.io/
      name: è®¿é—®Ralvineçš„åšå®¢
    - icon: fontawesome/brands/weibo
      link: https://ralvine.github.io/
      name: è®¿é—®Ralvineçš„åšå®¢
    - icon: fontawesome/brands/weixin
      link: https://ralvine.github.io/
      name: è®¿é—®Ralvineçš„åšå®¢
    - icon: fontawesome/brands/youtube
      link: https://ralvine.github.io/
      name: è®¿é—®Ralvineçš„åšå®¢
    - icon: fontawesome/brands/zhihu
      link: https://ralvine.github.io/
      name: è®¿é—®Ralvineçš„åšå®¢
extra_css:
  - extra.css
extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
nav:
  - ğŸ“å®¢å»Š: 'index.md'
  - ğŸ–‹ï¸èƒ¶å·: 'memo/index.md'
  - ğŸ“é•œè§‚: 'library/index.md'
  - ğŸ—’é‚»åŸŸ: 'notes/index.md'
  - ğŸ“šç›®ä½™: 'view/index.md'
  # secret: 'cyr-1'