site_name: MirInsider é•œå¹•
copyright: Copyright &copy; 2021-2022 Ralvine
site_url: https://ralvine.github.com/mirinsider/
theme:
  icon:
    logo: material/salesforce
  name: material
  favicon: images/favicon.png
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    #- navigation.tabs.sticky
    - navigation.indexes
    - navigation.top
    - navigation.expand
    - navigation.footer
    - search.highlight
    - search.share
  language: zh
  palette: 
    - primary: white
      toggle:
        icon: material/weather-sunny
        name: åˆ‡æ¢å¤œé—´æ¨¡å¼
    - scheme: slate
      primary: black
      toggle:
        icon: material/weather-night
        name: åˆ‡æ¢æ—¥é—´æ¨¡å¼
  font:
      text: Share Tech
      code: JetBrains Mono
markdown_extensions:
  - toc:
      permalink: true
      permalink_title: è·³è½¬åˆ°è¯¥éƒ¨åˆ†
  - meta
  - pymdownx.tabbed:
      alternate_style: true 
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      use_pygments: true
      linenums: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - attr_list
  - md_in_html
  - admonition
  - footnotes
  - def_list
  - pymdownx.details
  - pymdownx.superfences
plugins:
  - git-revision-date-localized:
      enable_creation_date: true
      type: iso_datetime
  - search
  - tags
  - tags:
      enabled: !ENV [CI, false]
      tags_file: tags.md
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://ralvine.github.io/
      name: è®¿é—®Ralvineçš„åšå®¢
    - icon: fontawesome/brands/alipay
      link: https://ralvine.github.io/
      name: è®¿é—®Ralvineçš„åšå®¢
    - icon: fontawesome/brands/apple
      link: https://ralvine.github.io/
      name: è®¿é—®Ralvineçš„åšå®¢
    - icon: fontawesome/brands/steam
      link: https://ralvine.github.io/
      name: è®¿é—®Ralvineçš„åšå®¢
    - icon: fontawesome/brands/telegram
      link: https://ralvine.github.io/
      name: è®¿é—®Ralvineçš„åšå®¢
    - icon: fontawesome/brands/twitter
      link: https://ralvine.github.io/
      name: è®¿é—®Ralvineçš„åšå®¢
    - icon: fontawesome/brands/weibo
      link: https://ralvine.github.io/
      name: è®¿é—®Ralvineçš„åšå®¢
    - icon: fontawesome/brands/weixin
      link: https://ralvine.github.io/
      name: è®¿é—®Ralvineçš„åšå®¢
    - icon: fontawesome/brands/youtube
      link: https://ralvine.github.io/
      name: è®¿é—®Ralvineçš„åšå®¢
    - icon: fontawesome/brands/zhihu
      link: https://ralvine.github.io/
      name: è®¿é—®Ralvineçš„åšå®¢
extra_css:
  - extra.css
extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
nav:
  - "ğŸ“å®¢å»Š":
    - index.md
    - "ğŸ‘¨ç®€ä»‹": brief.md
    - "ğŸ·ï¸æ ‡ç­¾": tags.md
  - "ğŸ–‹ï¸èƒ¶å·": 
    - memo/index.md
    - "æ—…è¡Œ":
      - memo/chuanyu.md
      - memo/tibet.md
    - "å…¬ç›ŠæœåŠ¡":
      - memo/mathqa22.md
      - memo/xncx.md
      - memo/zhijiao22.md
    - "å®è·µæ´»åŠ¨":
      - memo/highschool.md
      - memo/winter21.md
      - memo/winter22.md
    - "å­¦æœ¯é¡¹ç›®":
      - memo/tran.md
      - memo/apmcm.md
      - memo/mathshanshu.md
      - memo/mathshenzh.md
      - memo/mcm22.md
      - memo/modelzhcn.md
      - memo/modelzju.md
      - memo/srtp.md
    - "ç»„ç»‡å·¥ä½œ":
      - memo/test.md
      - "æ±‚æ˜¯æ½®å·¥ä½œå›¢é˜Ÿ":
        - memo/test.md
        - memo/test.md
      - "å›¢å§”å­¦ç”Ÿæ–‡ä½“ä¸­å¿ƒ":
        - memo/test.md
        - memo/test.md
      - "ä¿¡è®¡å…šæ”¯éƒ¨":
        - memo/test.md
        - memo/test.md
      - "ç«ºå¯æ¡¢å­¦é™¢ITP":
        - memo/test.md
        - memo/test.md
      - "ZJUMSC":
        - memo/test.md
  - "ğŸ“é•œè§‚": 
    - library/index.md
    - "è¯„è®º":
      - library/news-1.md
      - library/news-2.md
      - library/news-3.md
      - library/fsz-1.md
      - library/fsz-2.md
      - library/mks-1.md
      - library/mks-2.md
      - library/jzm-1.md
      - library/mqz-1.md
      - library/mqz-2.md
      - library/mqz-3.md
      - library/mzd-1.md
      - library/slz-1.md
      - library/slz-2.md
      - library/ygz-1.md
      - library/ygz-2.md
    - "æŠ¥é“":
      - library/hyb.md
      - library/tzhy.md
      - library/zfcg.md
      - library/ghth.md
      - library/jdgk.md
      - library/gkch.md
      - library/ldr.md
      - library/ldrtx.md
      - library/zyzfw.md
      - library/united-1.md
      - library/united-2.md
      - library/wqs-1.md
      - library/wqs-2.md
      - library/wqs-3.md
      - library/wjb-1.md
      - library/zjw-1.md
      - library/zjw-2.md
    - "æ–‡çŒ®":
      - library/xjp-1.md
      - library/xjp-2.md
      - library/xjp-3.md
      - library/xjp-4.md
      - library/xjp-5.md
      - library/xjp-6.md
      - library/zy23-1.md
  - "ğŸ—’é‚»åŸŸ": 
    - notes/index.md
    - "æµ™æ±Ÿå¤§å­¦æœ¬ç§‘ç”Ÿè¯¾ç¨‹":
      - "2022-2023ç§‹å†¬":
        - notes/data.md
        - notes/quan.md
        - notes/xigai.md
        - notes/eco.md
        - notes/na.md
        - notes/syms.md
        - notes/pde22.md
        - notes/gll.md
        - notes/alg.md
        - notes/soft.md
      - "2021-2022æ˜¥å¤":
        - notes/model.md
        - notes/pde.md
        - notes/tdgt.md
        - notes/szds.md
        - notes/mg.md
        - notes/ec.md
        - notes/junli.md
        - notes/guanli.md
      - "2021-2022ç§‹å†¬":
        - notes/ds.md
        - notes/sf3.md
        - notes/my.md
        - notes/ggjj.md
        - notes/dxwl2.md
        - notes/dxwlsy.md
        - notes/ode.md
      - "2020-2021æ˜¥å¤":
        - notes/wxqy.md
        - notes/dxwl.md
        - notes/jds.md
        - notes/xc.md
        - notes/sf2.md
        - notes/dxyy4.md
        - notes/zhigui.md
      - "2020-2021ç§‹å†¬":
        - notes/dxyy3.md
        - notes/sx.md
        - notes/sf.md
        - notes/skd.md
        - notes/skdsy.md
        - notes/mks.md
        - notes/jjf.md
        - notes/jihe.md
        - notes/djj.md
    - "è®¡ç®—æœºç§‘å­¦ä¸æŠ€æœ¯":
      - "äººå·¥æ™ºèƒ½&æœºå™¨å­¦ä¹ ":
        - notes/cs188.md
        - notes/cs229.md
      - "å¼€å‘":
        - notes/html-css.md
        - notes/docker.md
        - notes/note0.md
    - "æ•°åª’åˆ›ä½œ":
      - notes/webs.md
      - notes/fcpx.md
  - "ğŸ“šç›®ä½™": 
    - view/index.md
    - "ä¹¦ç±":
      - view/liucx.md
      - view/longnight.md
      - view/qpdzsgr.md
    - "éŸ³ä¹":
      - view/lyric.md
    - "è§†é¢‘":
      - view/surface.md